_DETECT_VISIT_PROMPT = """
 "Look at this document page image and extract exactly three values.\n\n"
                                "1) VISIT NUMBER (visit_number)\n"
                                "   - ONLY use a number that is explicitly the value for a field labeled:\n"
                                "     'Visit #', 'Visit #:', 'Visit Number', 'Visit No.', or the word 'Visit' followed by a number that is the visit identifier.\n"
                                "   - The number MUST appear next to or under such a label. It is the visit ID (e.g. 17, 26, 31), not a page index.\n"
                                "   - DO NOT use: numbers from 'Page 2', 'Page #: 2', 'p.2', '2 of 9', 'page 2 of 10', or any page counter. Those are PAGE numbers.\n"
                                "   - If you do not see a clearly labeled Visit # / Visit Number field, or you are unsure, return NONE for visit_number. Do not guess.\n\n"
                                "2) VISIT DATE (visit_date)\n"
                                "   - Use dates under labels like 'Visit Date','DOS', 'Date of Daily Note', 'Date of Visit', or 'Date'. Format as MM/DD/YYYY or Month DD, YYYY.\n"
                                "   - If not visible, return NONE.\n\n"
                                "3) PAGE NUMBER (page_number)\n"
                                "   - The numeric page of the document: from 'Page 1', 'Page #: 2', 'p.11', '1 of 89', etc. Return only the number (e.g. 1, 2, 11).\n"
                                "   - If not visible, return NONE.\n\n"
                                "Return ONLY three values separated by commas: visit_number,visit_date,page_number\n"
                                "Use NONE for any value not clearly present. Examples:\n"
                                "26,02/10/2020,7\n"
                                "NONE,12/26/2025,3\n"
                                "17,NONE,11\n"
                                "NONE,NONE,NONE\n"
                                "31,12/26/2025,NONE\n\n"
                                "CRITICAL: If the only number you see is from 'Page X' or 'p.X' or 'X of Y', do NOT put it in visit_number. Put it only in page_number, and use NONE for visit_number."
"""

